let D=db(),session=JSON.parse(localStorage.getItem("simpras_session")||"null");
const A=document.getElementById("app"), $=s=>document.querySelector(s);
const user=()=>session&&D.users.find(x=>x.id===session.id), admin=()=>user()?.role==="admin";
const id=p=>p+Date.now().toString(36)+Math.random().toString(36).slice(2,5);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const status=s=>`<span class="badge ${s==="Tersedia"||s==="Disetujui"?"ok":s==="Menunggu"||s==="Terbatas"?"wait":s==="Ditolak"||s==="Tidak Tersedia"?"bad":"off"}">${esc(s)}</span>`;
function act(text,target=""){D.activities.unshift({id:id("a"),text,target,time:new Date().toLocaleString("id-ID")});D.activities=D.activities.slice(0,100);save(D)}
function notif(uid,title,msg){D.notifications.unshift({id:id("n"),uid,title,msg,time:new Date().toLocaleString("id-ID"),read:false});save(D)}
function shell(title,body,active){
const nav=admin()?[['home','Dashboard'],['sarana','Sarana'],['prasarana','Prasarana'],['requests','Pengajuan'],['jadwal','Jadwal'],['users','Pengguna'],['report','Laporan'],['activity','Riwayat Aktivitas']]:[['home','Dashboard'],['sarana','Sarana'],['prasarana','Prasarana'],['request','Ajukan Peminjaman'],['jadwal','Jadwal'],['history','Riwayat'],['notif','Notifikasi']];
const u=user();
A.innerHTML=`<div class="shell"><aside><div class="brand"><b>SIMPRAS</b><small>Manajemen Sarpras</small></div><div class="profile"><strong>👤 ${esc(u.name)}</strong><small>${esc(admin()?"Admin Sarpras":u.org)}</small><div class="account-actions"><button onclick="switchAccount()">🔄 Ganti Akun</button><button onclick="logout()">🚪 Logout</button></div></div><nav>${nav.map(n=>`<button class="${active===n[0]?"active":""}" onclick="go('${n[0]}')">◼ ${n[1]}</button>`).join("")}</nav></aside><main><header><div><small>SIMPRAS / ${esc(title)}</small><h1>${esc(title)}</h1></div><div class="header-account"><span>👤 ${esc(u.name)}</span><button onclick="switchAccount()">🔄 Ganti Akun</button></div></header><section>${body}</section></main></div>`}
function login(){A.innerHTML=`<div class="login"><div class="hero"><b>SIMPRAS</b><h1>Manajemen Sarana dan Prasarana Sekolah</h1><p>Kelola sarana, prasarana, pengajuan, jadwal, dan riwayat dalam satu aplikasi.</p></div><div class="form"><h2>Masuk ke SIMPRAS</h2><p>Gunakan akun demo di bawah.</p><form onsubmit="loginDo(event)"><label>Username<input id="u" required></label><label>Password<input id="p" type="password" required></label><button>Masuk →</button></form><div id="err"></div><div class="demo"><b>Akun demo</b><br>admin / adminsarpras<br>osis / osis123<br>pramuka / pramuka123<br>pmr / pmr123</div></div></div>`}
function loginDo(e){e.preventDefault();let x=D.users.find(u=>u.username===$("#u").value.trim()&&u.password===$("#p").value&&u.active);if(!x){$("#err").textContent="Username atau password salah.";return}session={id:x.id};localStorage.setItem("simpras_session",JSON.stringify(session));go("home")}
function clearSession(){localStorage.removeItem("simpras_session");session=null}
function logout(){if(!session)return login();if(confirm(`Yakin ingin logout dari akun ${user()?.name||"ini"}?`)){clearSession();login()}}
function switchAccount(){if(confirm("Ganti akun akan mengakhiri sesi akun saat ini. Data sarana dan prasarana tetap aman. Lanjutkan?")){clearSession();login()}}
function go(p){if(!user())return login();({home:home,sarana:sarana,prasarana:prasarana,requests:requests,jadwal:jadwal,users:users,report:report,activity:activity,request:requestForm,history:history,notif:notifPage}[p]||home)()}
function stats(){return `<div class="stats"><div><small>Total Sarana</small><b>${D.sarana.length}</b></div><div><small>Total Prasarana</small><b>${D.prasarana.length}</b></div><div><small>Menunggu</small><b>${D.requests.filter(x=>x.status==="Menunggu").length}</b></div><div><small>Disetujui</small><b>${D.requests.filter(x=>x.status==="Disetujui").length}</b></div></div>`}
function home(){let mine=D.requests.filter(x=>x.uid===user().id);shell("Dashboard",stats()+`<div class="welcome"><div><b>Halo, ${esc(user().name)} 👋</b><p>${admin()?"Kelola data dan pengajuan sarpras sekolah.":"Cek ketersediaan sarpras dan ajukan peminjaman."}</p></div><button onclick="go('${admin()?"requests":"request"}')">${admin()?"Lihat Pengajuan":"＋ Ajukan Peminjaman"}</button></div><div class="grid"><div class="card"><h3>${admin()?"Pengajuan Terbaru":"Pengajuan Saya"}</h3>${table(admin()?D.requests.slice(0,6):mine.slice(0,6),admin())}</div><div class="card"><h3>Aktivitas Terbaru</h3>${D.activities.slice(0,8).map(x=>`<div class="activity"><b>${esc(x.text)}</b><small>${esc(x.target)} • ${esc(x.time)}</small></div>`).join("")||"<p class='muted'>Belum ada aktivitas.</p>"}</div></div>`,"home")}
function table(arr,isAdmin){if(!arr.length)return "<p class='muted'>Belum ada data.</p>";return `<div class="table"><table><tr><th>Peminjam</th><th>Item</th><th>Jadwal</th><th>Status</th>${isAdmin?"<th></th>":""}</tr>${arr.map(r=>{let u=D.users.find(x=>x.id===r.uid),it=r.sid?D.sarana.find(x=>x.id===r.sid):D.prasarana.find(x=>x.id===r.pid);return `<tr><td>${esc(u?.org||u?.name)}</td><td>${esc(it?.name)}</td><td>${esc(r.date)}<br>${esc(r.start)}-${esc(r.end)}</td><td>${status(r.status)}</td>${isAdmin?`<td><button class="mini" onclick="decide('${r.id}')">Detail</button></td>`:""}</tr>`}).join("")}</table></div>`}
function assetCard(x,kind){let can=!admin()&&x.status==="Tersedia"&&(kind==="sarana"?x.avail>0:true);return `<article class="asset"><div class="photo">${kind==="sarana"?"▣":"⌂"}</div><div class="pad"><div class="row"><h3>${esc(x.name)}</h3>${status(x.status)}</div><small>${esc(kind==="sarana"?x.cat:x.type)} • ${esc(x.location)}</small><p>${esc(x.desc)}</p><div class="meta">${kind==="sarana"?`Jumlah <b>${x.qty}</b> • Tersedia <b>${x.avail}</b>`:`Kapasitas <b>${x.capacity}</b>`}</div>${admin()?`<button class="mini" onclick="${kind}Form('${x.id}')">Edit</button> <button class="mini danger" onclick="delAsset('${kind}','${x.id}')">Hapus</button>`:`<button class="wide" ${can?`onclick="requestForm('${kind}','${x.id}')"`:"disabled"}>${can?"Ajukan Peminjaman":"Tidak Tersedia"}</button>`}</div></article>`}
function sarana(){shell("Sarana",`<div class="pagehead"><p>Peralatan dan perlengkapan sekolah.</p>${admin()?`<button onclick="saranaForm()">＋ Tambah Sarana</button>`:""}</div><div class="assets">${D.sarana.map(x=>assetCard(x,"sarana")).join("")}</div>`,"sarana")}
function prasarana(){shell("Prasarana",`<div class="pagehead"><p>Ruang, gedung, dan fasilitas sekolah.</p>${admin()?`<button onclick="prasaranaForm()">＋ Tambah Prasarana</button>`:""}</div><div class="assets">${D.prasarana.map(x=>assetCard(x,"prasarana")).join("")}</div>`,"prasarana")}
function modal(html){document.querySelector(".modal-bg")?.remove();document.body.insertAdjacentHTML("beforeend",`<div class="modal-bg" onclick="if(event.target===this)this.remove()"><div class="modal">${html}</div></div>`)}
function fields(x,kind){return `<div class="fields"><label>Nama<input name="name" value="${esc(x.name||"")}" required></label><label>${kind==="sarana"?"Kategori":"Jenis"}<input name="cat" value="${esc(x.cat||x.type||"")}"></label>${kind==="sarana"?`<label>Jumlah<input name="qty" type="number" value="${x.qty||1}" min="0"></label><label>Jumlah tersedia<input name="avail" type="number" value="${x.avail??1}" min="0"></label>`:`<label>Kapasitas<input name="capacity" type="number" value="${x.capacity||0}" min="0"></label>`}<label>Kondisi<select name="condition">${["Baik","Rusak Ringan","Rusak Berat"].map(v=>`<option ${x.condition===v?"selected":""}>${v}</option>`).join("")}</select></label><label>Status<select name="status">${["Tersedia","Terbatas","Tidak Tersedia","Rusak"].map(v=>`<option ${x.status===v?"selected":""}>${v}</option>`).join("")}</select></label><label>Lokasi<input name="location" value="${esc(x.location||"")}"></label><label class="span">Deskripsi<textarea name="desc">${esc(x.desc||"")}</textarea></label></div>`}
function saranaForm(i=""){let x=i?D.sarana.find(a=>a.id===i):{};modal(`<h2>${i?"Edit":"Tambah"} Sarana</h2><form onsubmit="saveAsset(event,'sarana','${i}')">${fields(x,"sarana")}<button>Simpan</button></form>`)}
function prasaranaForm(i=""){let x=i?D.prasarana.find(a=>a.id===i):{};modal(`<h2>${i?"Edit":"Tambah"} Prasarana</h2><form onsubmit="saveAsset(event,'prasarana','${i}')">${fields(x,"prasarana")}<button>Simpan</button></form>`)}
function saveAsset(e,k,i){e.preventDefault();let f=Object.fromEntries(new FormData(e.target)),arr=k==="sarana"?D.sarana:D.prasarana,x=i?arr.find(a=>a.id===i):{id:id(k[0])};Object.assign(x,{name:f.name,condition:f.condition,status:f.status,location:f.location,desc:f.desc});if(k==="sarana")Object.assign(x,{cat:f.cat,qty:+f.qty,avail:Math.min(+f.avail,+f.qty)});else Object.assign(x,{type:f.cat,capacity:+f.capacity});if(!i)arr.push(x);save(D);act(`${i?"Admin mengubah":"Admin menambahkan"} ${k}`,x.name);D.users.filter(u=>u.role==="peminjam").forEach(u=>notif(u.id,`${k==="sarana"?"Sarana":"Prasarana"} diperbarui`,`${x.name}: ${x.status}`));e.target.closest(".modal-bg").remove();k==="sarana"?sarana():prasarana()}
function delAsset(k,i){let arr=k==="sarana"?D.sarana:D.prasarana,x=arr.find(a=>a.id===i);if(confirm("Hapus "+x.name+"?")){if(k==="sarana")D.sarana=arr.filter(a=>a.id!==i);else D.prasarana=arr.filter(a=>a.id!==i);save(D);act("Admin menghapus "+k,x.name);k==="sarana"?sarana():prasarana()}}
function requestForm(kind="sarana",selected=""){if(admin())return requests();let arr=kind==="sarana"?D.sarana:D.prasarana;shell("Ajukan Peminjaman",`<div class="card formcard"><h3>Form Pengajuan</h3><form onsubmit="submitReq(event)"><label>Jenis<select name="kind" onchange="changeOptions(this.value)"><option ${kind==="sarana"?"selected":""}>sarana</option><option ${kind==="prasarana"?"selected":""}>prasarana</option></select></label><label>Aset<select id="asset" name="asset">${arr.map(x=>`<option value="${x.id}" ${x.id===selected?"selected":""}>${esc(x.name)} — ${esc(x.status)}</option>`).join("")}</select></label><div class="fields"><label>Tanggal<input type="date" name="date" required></label><label>Jam mulai<input type="time" name="start" required></label><label>Jam selesai<input type="time" name="end" required></label></div><label>Keperluan<textarea name="purpose" required></textarea></label><button>Kirim Pengajuan</button></form></div>`,"request")}
function changeOptions(k){let arr=k==="sarana"?D.sarana:D.prasarana;$("#asset").innerHTML=arr.map(x=>`<option value="${x.id}">${esc(x.name)} — ${esc(x.status)}</option>`).join("")}
function submitReq(e){e.preventDefault();let f=Object.fromEntries(new FormData(e.target)),arr=f.kind==="sarana"?D.sarana:D.prasarana,x=arr.find(a=>a.id===f.asset);if(x.status!=="Tersedia")return alert("Aset tidak tersedia.");if(f.start>=f.end)return alert("Jam selesai harus lebih besar.");let conflict=D.requests.some(r=>r.status==="Disetujui"&&r.date===f.date&&r.start<f.end&&f.start<r.end&&((f.kind==="sarana"&&r.sid===f.asset)||(f.kind==="prasarana"&&r.pid===f.asset)));if(conflict)return alert("Jadwal bentrok.");let r={id:id("r"),uid:user().id,sid:f.kind==="sarana"?f.asset:null,pid:f.kind==="prasarana"?f.asset:null,date:f.date,start:f.start,end:f.end,purpose:f.purpose,status:"Menunggu"};D.requests.unshift(r);save(D);act(`${user().org} mengajukan peminjaman`,x.name);notif("u1","Pengajuan baru",`${user().org} mengajukan ${x.name}`);alert("Pengajuan berhasil.");go("history")}
function requests(){shell("Pengajuan",`<div class="card">${table(D.requests,true)}</div>`,"requests")}
function decide(i){let r=D.requests.find(x=>x.id===i),x=r.sid?D.sarana.find(a=>a.id===r.sid):D.prasarana.find(a=>a.id===r.pid),u=D.users.find(a=>a.id===r.uid);modal(`<h2>Detail Pengajuan</h2><p><b>${esc(u.org)}</b> • ${esc(x.name)}</p><p>${esc(r.date)} ${esc(r.start)}-${esc(r.end)}</p><p>${esc(r.purpose)}</p><div class="actions"><button class="danger" onclick="setReq('${i}','Ditolak')">Tolak</button><button onclick="setReq('${i}','Disetujui')">Setujui</button></div>`)}
function setReq(i,s){let r=D.requests.find(x=>x.id===i),x=r.sid?D.sarana.find(a=>a.id===r.sid):D.prasarana.find(a=>a.id===r.pid);if(s==="Disetujui"){let conflict=D.requests.some(q=>q.id!==i&&q.status==="Disetujui"&&q.date===r.date&&q.start<r.end&&r.start<q.end&&((r.sid&&q.sid===r.sid)||(r.pid&&q.pid===r.pid)));if(conflict)return alert("Jadwal bentrok.");if(x.status!=="Tersedia")return alert("Aset sudah tidak tersedia.");if(r.sid){x.avail=Math.max(0,x.avail-1);if(!x.avail)x.status="Tidak Tersedia"}}r.status=s;save(D);act(`Admin ${s.toLowerCase()} pengajuan`,x.name);notif(r.uid,`Pengajuan ${s}`,`${x.name} ${s.toLowerCase()}.`);document.querySelector(".modal-bg")?.remove();requests()}
function history(){let a=D.requests.filter(x=>x.uid===user().id);shell("Riwayat",`<div class="card">${table(a,false)}</div>`,"history")}
function jadwal(){let a=D.requests.filter(x=>x.status==="Disetujui");shell("Jadwal",`<div class="card">${a.length?a.map(r=>{let x=r.sid?D.sarana.find(a=>a.id===r.sid):D.prasarana.find(a=>a.id===r.pid);return `<div class="schedule"><b>${esc(r.date)}</b><span>${esc(r.start)}-${esc(r.end)}</span><strong>${esc(x.name)}</strong>${status(r.status)}</div>`}).join(""):"<p class='muted'>Belum ada jadwal.</p>"}</div>`,"jadwal")}
function users(){shell("Pengguna",`<div class="card table">${table(D.users.map(u=>({uid:u.id,status:u.active?"Aktif":"Nonaktif",date:"",start:"",end:"",purpose:u.org,sid:null,pid:null})),false)}</div>`,"users")}
function report(){shell("Laporan",stats()+`<div class="card"><h3>Ringkasan Penggunaan</h3>${D.sarana.map(x=>`<p>${esc(x.name)} — digunakan ${x.qty-x.avail}</p>`).join("")}</div>`,"report")}
function activity(){shell("Riwayat Aktivitas",`<div class="card">${D.activities.map(x=>`<div class="activity"><b>${esc(x.text)}</b><small>${esc(x.target)} • ${esc(x.time)}</small></div>`).join("")||"<p class='muted'>Belum ada aktivitas.</p>"}`,"activity")}
function notifPage(){let n=D.notifications.filter(x=>x.uid===user().id);shell("Notifikasi",`<div class="card">${n.map(x=>`<div class="activity"><b>${esc(x.title)}</b><p>${esc(x.msg)}</p><small>${esc(x.time)}</small></div>`).join("")||"<p class='muted'>Belum ada notifikasi.</p>"}`,"notif")}
window.go=go;window.logout=logout;window.switchAccount=switchAccount;window.loginDo=loginDo;window.saranaForm=saranaForm;window.prasaranaForm=prasaranaForm;window.saveAsset=saveAsset;window.delAsset=delAsset;window.requestForm=requestForm;window.submitReq=submitReq;window.changeOptions=changeOptions;window.requests=requests;window.decide=decide;window.setReq=setReq;
if(user())go("home");else login();
